### ISSUE TITLE
BUG: Fabric does not work with this launcher.

### ISSUE THREAD

**Issue by zaphod77** [rakion99/minecraftlauncher#10]
While i can install it uing the fabric installer, and it says it is installed. i cannot get it to start. I get an exception error.  additionally, if i pick teh "restore" choice in version management, the version vanishes completely, and has to be reinstalled.  Normal 1.19 works fine.

**Comment by zaphod77** [comment]
i had to delete the .minecraft and java directories, but then i was able to get it to work again.  that was strange.

**Comment by rakion99** [comment]
maybe u had a old mod in mods folder or something idk, im still testing fabric as i never used it lol

**Comment by zaphod77** [comment]
no i didn't. i tried to fix things by copying files from another installation, and it broke things so badly i had to literally delete everything (but unmodded still worked fine).
