### ISSUE TITLE
System.ArgumentNullException

### ISSUE THREAD

**Issue by Vamashi** [rakion99/minecraftlauncher#11]
On start i'm getting System.ArgumentNullException.
This exception was originally thrown at this call stack:
    [External Code]
    FreeLauncher.Forms.LauncherForm.UpdateVersionListView() in LauncherForm.cs
    FreeLauncher.Forms.LauncherForm.profilesDropDownBox_SelectedIndexChanged(object, Telerik.WinControls.UI.Data.PositionChangedEventArgs) in LauncherForm.cs
    [External Code]
    FreeLauncher.Forms.LauncherForm.UpdateProfileList() in LauncherForm.cs
    FreeLauncher.Forms.LauncherForm.LauncherForm(FreeLauncher.Configuration) in LauncherForm.cs
    FreeLauncher.Program.VersionCheck(string[]) in Program.cs
    FreeLauncher.Program.Main(string[]) in Program.cs

**Comment by rakion99** [comment]
hmmm could be that one version in your .minecraft/versions folder is missing another version like a mod that requires 1.xx but you dont have it installed or the json is corrupted

**Comment by rakion99** [comment]
now i got the error, is because it was skipping the language file check at start should be fixed in this commit 3ba3182f66cbdcb326ad7e6899dd63d85f815568
