### ISSUE TITLE
You should use .NET Core

### ISSUE THREAD

**Issue by rblxploit** [rakion99/minecraftlauncher#2]
Because Minecraft is for Windows, Mac and Linux, i think you should use .NET Core which is compatible with all of them. The user just needs to install .NET Core, but before using the program if he does not have it he would be prompted to install it.

**Comment by rakion99** [comment]
maybe in the future or maybe not since i wont use linux and even less mac
but dedepete already made his dotmclauncher for .Net Core so you can make your own launcher https://github.com/dedepete/dotMCLauncher
